// Demo patient records for the casebook. PLACEHOLDER FIXTURES from Ben's
// mockup (Whitmore) plus three drafts in the same shape — names, complaints,
// and treatments all need Ben's review before they become content. The real
// patient system (generatePatient, consultation results) replaces this file.

export const demoPatients = [
  {
    id: 'pt-whitmore',
    name: 'Miss Clara Whitmore',
    age: 27,
    sex: 'Female',
    silhouette: 'woman',
    listDate: 'May 14, 1896',
    diagnosis: 'Neurasthenia',
    address: '48 Waverly Place,\nNew York, NY',
    occupation: 'Schoolteacher',
    maritalStatus: 'Single',
    firstVisit: 'May 14, 1896',
    referredBy: '—',
    complaint: 'Exhaustion of mind and body, nervous debility, and inability to concentrate; headaches.',
    symptoms: 'Mental fatigue, palpitations, poor appetite, sleeplessness, languor, occasional tremulousness. Pupils normal. No organic disease detected.',
    treatment: 'Rest cure. Nutritious diet. Bromide of Potassium (10 gr.) at bedtime. Massage twice weekly. Fresh air and light exercise as tolerated.',
    progress: 'Improved sleep reported. Less nervous irritability. Continue regimen. Prognosis favorable with sustained rest and avoidance of mental strain.',
    visits: [
      { date: 'May 14, 1896', kind: 'Interview', notes: 'Initial consultation. Complaints of exhaustion and nervous weakness.' },
      { date: 'May 16, 1896', kind: 'Examination', notes: 'Physical exam unremarkable. No signs of organic disease. Diagnosis: Neurasthenia.' },
      { date: 'May 21, 1896', kind: 'Follow-Up', notes: 'Slight improvement in sleep and appetite. Continue rest cure and regimen.' },
      { date: 'May 28, 1896', kind: 'Treatment Adjusted', notes: 'Added Hydrotherapy twice weekly. Continue bromide. Avoid correspondence.' },
    ],
  },
  {
    id: 'pt-davenport',
    name: 'Mr. Henry Davenport',
    age: 45,
    sex: 'Male',
    silhouette: 'man',
    listDate: 'May 12, 1896',
    diagnosis: 'Functional Dyspepsia',
    address: '211 East 17th Street,\nNew York, NY',
    occupation: 'Dry-goods merchant',
    maritalStatus: 'Married',
    firstVisit: 'May 12, 1896',
    referredBy: 'Dr. T. H. Colton',
    complaint: 'Distress after meals, flatulence, and a gnawing at the pit of the stomach; low spirits over business affairs.',
    symptoms: 'Tongue coated, appetite capricious, bowels irregular. No tenderness suggesting organic lesion. Sleep broken by worry.',
    treatment: 'Regulated diet: small meals, no fried food, no iced water. Pepsin with bismuth before meals. A daily walk after dinner.',
    progress: 'Reports the gnawing much abated. Still eats too quickly. Diet held to imperfectly; admonished.',
    visits: [
      { date: 'May 12, 1896', kind: 'Interview', notes: 'Initial consultation. Dyspeptic complaints of two years’ standing.' },
      { date: 'May 19, 1896', kind: 'Follow-Up', notes: 'Improvement with diet. Continue regimen; review in a fortnight.' },
    ],
  },
  {
    id: 'pt-vanwyck',
    name: 'Mrs. Eleanor Van Wyck',
    age: 36,
    sex: 'Female',
    silhouette: 'woman',
    listDate: 'May 8, 1896',
    diagnosis: 'Hysteria',
    address: '14 Washington Square North,\nNew York, NY',
    occupation: '—',
    maritalStatus: 'Married',
    firstVisit: 'May 8, 1896',
    referredBy: 'Dr. S. Weir Mitchell',
    complaint: 'Globus, fits of weeping without occasion, and numbness of the left arm that comes and goes.',
    symptoms: 'Sensory complaints shift on repeated examination. Grip strong when attention is diverted. General health good.',
    treatment: 'Rest, seclusion from sympathetic visitors, and a full diet after Mitchell. Massage and electricity to the arm.',
    progress: 'The arm recovers under faradization. Household circumstances bear looking into; the husband is to call.',
    visits: [
      { date: 'May 8, 1896', kind: 'Interview', notes: 'Referred from Philadelphia. Long history of shifting complaints.' },
      { date: 'May 11, 1896', kind: 'Examination', notes: 'No organic signs. Diagnosis: hysteria. Rest treatment begun.' },
      { date: 'May 25, 1896', kind: 'Follow-Up', notes: 'Weeping fits fewer. Arm numbness returns when visitors call.' },
    ],
  },
  {
    id: 'pt-remington',
    name: 'Mr. Charles Remington',
    age: 52,
    sex: 'Male',
    silhouette: 'bearded',
    listDate: 'May 6, 1896',
    diagnosis: 'Melancholia',
    address: '390 Lexington Avenue,\nNew York, NY',
    occupation: 'Retired broker',
    maritalStatus: 'Widower',
    firstVisit: 'May 6, 1896',
    referredBy: '—',
    complaint: 'Settled gloom since the loss of his wife in the winter; early waking; conviction that his affairs are ruined, though they are sound.',
    symptoms: 'Weight fallen a stone since January. Speech slow, self-reproachful. Denies any design against his own life; watchfulness advised.',
    treatment: 'Nourishment pressed at regular hours. Companionship arranged; his brother to stay in the house. Review twice weekly.',
    progress: 'Takes his meals with urging. The early waking persists. Brother reports him quieter in the evenings.',
    visits: [
      { date: 'May 6, 1896', kind: 'House Call', notes: 'Seen at home at the brother’s request. Profound dejection.' },
      { date: 'May 9, 1896', kind: 'Examination', notes: 'Bodily health fair for his years. Diagnosis: melancholia.' },
      { date: 'May 13, 1896', kind: 'Follow-Up', notes: 'No worse. Watchfulness maintained. Diet pressed.' },
    ],
  },
];
