import { generatePatient, patientToRendererCRecipe } from '../../../../shared/patients/index.js';
import { createActorInstance } from '../../world/characters/actors.js';

const id = 'nora-byrne-1896';
const base = generatePatient({ seed: 2273, sex: 'female' });

const profile = Object.freeze({
  ...base,
  identity: Object.freeze({
    ...base.identity,
    age: 28,
    birthYear: 1868,
    givenName: 'Nora',
    familyName: 'Byrne',
    title: 'Miss',
    displayName: 'Miss Byrne',
    fullName: 'Miss Nora Byrne',
    origin: Object.freeze({
      id: 'irish-american', label: 'Irish American', generation: 1,
      generationLabel: 'born in New York to Irish parents',
    }),
    migration: null,
    religion: 'Roman Catholic',
    language: 'English',
  }),
  social: Object.freeze({
    ...base.social,
    classId: 'working',
    classLabel: 'self-supporting working household',
    occupationId: 'copyist',
    occupation: 'copyist in a law office',
    householdPosition: 'boarder',
    household: Object.freeze({ maritalStatus: 'single', spouseOccupation: null, spouseDeceased: false, children: 0, dependents: 0 }),
    residence: 'a boarding house in Greenwich Village',
    payer: 'private account',
    referralSource: 'her boarding-house keeper',
  }),
  clinical: Object.freeze({
    id: 'nora-dissociative-presentation',
    periodCategory: 'hysteria with cerebral automatism',
    theme: 'amnesia, automatic writing, and functional sensory symptoms after bereavement',
    presentingComplaint: 'poor sleep and trembling hands',
    symptoms: ['broken sleep', 'fine hand tremor', 'automatic writing', 'brief periods of missing time', 'variable numbness of the left hand'],
    duration: 'six months',
    severity: 0.62,
    affect: 'guarded',
    flags: ['research-draft', 'authored-composite'],
    performance: Object.freeze({
      posture: -0.08, breathing: 1.08, breathingRate: 16, fidget: 1.28,
      gazeDrift: 1.32, weightShift: 1.05, tremor: 0.58, handTension: 0.72,
      gestureSpeed: 1.05,
    }),
  }),
});

const recipe = patientToRendererCRecipe(profile, {
  id,
  asset: {
    kind: 'authored-character',
    path: '/models/characters/nora-byrne.glb?v=3',
    applyRecipe: false,
    opaque: true,
    modelRotationX: -Math.PI / 2,
    motionClips: [
      'ClinicIdle', 'SittingTalking', 'SittingSelfSoothing',
    ],
    clipMap: {
      'clinic-idle': 'ClinicIdle',
      'sitting-talking': 'SittingTalking',
      'sitting-distressed': 'SittingSelfSoothing',
      'sitting-disapproval': 'SittingSelfSoothing',
      'sitting-disbelief': 'SittingSelfSoothing',
      'sitting-self-soothing': 'SittingSelfSoothing',
      'sit-down': 'ClinicIdle',
      'stand-up': 'ClinicIdle',
      'standing-idle': 'ClinicIdle',
      walk: 'ClinicIdle',
    },
  },
  animation: { body: 'clinic-idle', expression: 'guarded', gaze: 'doctor', speaking: false },
  // Use the same chair anchor and facing as the procedural female patients.
  // Asset-axis correction belongs on the model, not in its room placement.
  placement: { position: [0.45, 0.22, -1.7], rotation: [0, Math.PI, 0], scale: 1.82 },
});

const actor = createActorInstance({ id, recipe });

const facts = Object.freeze([
  Object.freeze({
    id: 'nora-sleep', kind: 'symptom', label: 'Broken sleep',
    value: 'Her sleep has been broken for several months, with no fixed hour of waking.',
    notebookSummary: 'Patient wakes repeatedly in the night and is exhausted by morning.',
    patientWording: 'I fall asleep from weariness, but wake again and again before morning.',
    disclosure: 'open', confidence: 'high', measurement: false,
    releaseOn: ['sleep', 'night', 'wake', 'dream'], noteTerms: ['sleep', 'waking', 'insomnia'],
  }),
  Object.freeze({
    id: 'nora-tremor', kind: 'symptom', label: 'Hand tremor',
    value: 'A fine tremor comes and goes in both hands and becomes more marked when she is watched.',
    notebookSummary: 'Hand tremor becomes more marked when the patient is watched.',
    patientWording: 'The shaking is worse when someone fixes their eyes upon my hands.',
    disclosure: 'open', confidence: 'moderate', measurement: false,
    releaseOn: ['tremor', 'shake', 'shaking', 'hands'], noteTerms: ['tremor', 'shaking', 'hands'],
  }),
  Object.freeze({
    id: 'nora-work-risk', kind: 'social', label: 'Work and lodging',
    value: 'She supports herself as a copyist; prolonged seclusion would cost her position and probably her room.',
    notebookSummary: 'Patient depends on copyist wages for her room and cannot afford prolonged rest.',
    patientWording: 'If I am kept from the office, I cannot pay Mrs. Doyle for my room. There is no family purse to fall back upon.',
    disclosure: 'withheld', confidence: 'high', measurement: false,
    releaseOn: ['work', 'office', 'copyist', 'money', 'room', 'rest'], noteTerms: ['work', 'copyist', 'office', 'lodging', 'room'],
  }),
  Object.freeze({
    id: 'nora-bereavement', kind: 'history', label: 'Bereavement',
    value: 'Her elder sister Mary died after a short illness in January 1896; the sleep disturbance began soon afterward.',
    notebookSummary: 'Sleep disturbance worsened around her sister Mary’s illness and death in January.',
    patientWording: 'My sister Mary died in January. I began waking in the night not long after we buried her.',
    disclosure: 'withheld', confidence: 'high', measurement: false,
    releaseOn: ['sister', 'mary', 'death', 'died', 'grief', 'loss', 'began', 'onset'],
    noteTerms: ['sister', 'mary', 'death', 'bereavement', 'grief'],
  }),
  Object.freeze({
    id: 'nora-seance', kind: 'context', label: 'Séance circle',
    value: 'A fellow boarder brought her to a small spiritualist circle, where attention settled on the movement of her hand.',
    notebookSummary: 'A fellow boarder brought the patient to a spiritualist circle where her hand was watched for signs from Mary.',
    patientWording: 'Mrs. Bell took me to a circle. They said the movement of my hand might mean that Mary wished to speak.',
    disclosure: 'withheld', confidence: 'high', measurement: false,
    minimumTrust: 50, requiresFactIds: ['nora-bereavement'],
    releaseOn: ['séance', 'seance', 'circle', 'spiritualist', 'spirit', 'dead'],
    noteTerms: ['séance', 'seance', 'circle', 'spiritualist'],
  }),
  Object.freeze({
    id: 'nora-automatic-writing', kind: 'symptom', label: 'Automatic writing',
    value: 'When a pencil is placed in her left hand during the circle, the hand sometimes writes short phrases without a felt intention to write.',
    notebookSummary: 'Patient says her left hand writes while she feels she is only watching it.',
    patientWording: 'With the pencil in my left hand, words sometimes come while I feel as though I am merely watching it move.',
    disclosure: 'withheld', confidence: 'high', measurement: false,
    minimumTrust: 52,
    releaseOn: ['write', 'writing', 'pencil', 'hand move', 'without intending', 'automatic'],
    noteTerms: ['writing', 'pencil', 'automatic', 'intention'],
  }),
  Object.freeze({
    id: 'nora-missing-time', kind: 'symptom', label: 'Missing time',
    value: 'On three occasions she found that ten to twenty minutes had passed without a continuous memory of them, although witnesses described quiet, purposeful behavior.',
    notebookSummary: 'Patient reports three gaps of ten to twenty minutes despite apparently purposeful behavior.',
    patientWording: 'Three times I have come to myself with part of the hour gone. They tell me I answered sensibly and put things in order, but I remember none of it.',
    disclosure: 'withheld', confidence: 'moderate', measurement: false,
    minimumTrust: 58, requiresFactIds: ['nora-automatic-writing'],
    releaseOn: ['memory', 'remember', 'time', 'hour', 'lost', 'missing', 'come to'],
    noteTerms: ['memory', 'amnesia', 'missing time', 'hour'],
  }),
  Object.freeze({
    id: 'nora-message-limits', kind: 'context', label: 'Contents of the writing',
    value: 'The writing uses Mary’s name but contains only family phrases and facts Nora already knew.',
    notebookSummary: 'The writings use Mary’s name and familiar phrases but reveal nothing unknown to the patient.',
    patientWording: 'It signs Mary’s name and uses sayings of ours, but it has told us nothing that was unknown to me before.',
    disclosure: 'withheld', confidence: 'high', measurement: false,
    requiresFactIds: ['nora-automatic-writing'],
    releaseOn: ['message', 'messages', 'words', 'said', 'know', 'unknown', 'mary'],
    noteTerms: ['message', 'writing', 'known', 'family phrases'],
  }),
  Object.freeze({
    id: 'nora-seizure-negatives', kind: 'history', label: 'No convulsive markers',
    value: 'She reports no convulsion, dangerous fall, tongue injury, incontinence, or prolonged confusion after an episode.',
    notebookSummary: 'No falls, convulsions, tongue injury, incontinence, or confusion follow the episodes.',
    patientWording: 'I have never fallen in a fit, bitten my tongue, or lost control of myself. I am not dazed afterward—only frightened by the gap.',
    disclosure: 'withheld', confidence: 'moderate', measurement: false,
    requiresFactIds: ['nora-missing-time'],
    releaseOn: ['fit', 'seizure', 'tongue', 'fall', 'confusion', 'convulsion'],
    noteTerms: ['convulsion', 'tongue', 'incontinence', 'confusion', 'seizure'],
  }),
  Object.freeze({
    id: 'nora-observed-tremor', kind: 'sign', label: 'Observed tremor',
    value: 'A fine irregular tremor is visible with the arms extended. It diminishes while her attention is occupied by a counting task.',
    disclosure: 'observed', confidence: 'moderate', measurement: false,
    noteTerms: ['tremor', 'attention', 'counting', 'diminishes'],
  }),
  Object.freeze({
    id: 'nora-sensory-pattern', kind: 'sign', label: 'Left-hand sensation',
    value: 'Pin and light touch are reported as dull over the left hand in a glove-like boundary that does not follow a single nerve or root.',
    disclosure: 'observed', confidence: 'moderate', measurement: false,
    noteTerms: ['sensation', 'numbness', 'glove', 'left hand'],
  }),
  Object.freeze({
    id: 'nora-normal-neurology', kind: 'sign', label: 'Strength and reflexes',
    value: 'Strength is full with encouragement; tendon reflexes are equal, and there is no wasting or fixed weakness.',
    disclosure: 'observed', confidence: 'high', measurement: false,
    noteTerms: ['strength', 'reflexes', 'wasting', 'weakness'],
  }),
  Object.freeze({
    id: 'nora-thyroid-negative', kind: 'sign', label: 'Pulse and neck',
    value: 'Pulse is 78 and regular. There is no visible enlargement of the thyroid, eye prominence, or marked loss of weight.',
    disclosure: 'observed', confidence: 'high', measurement: true,
    noteTerms: ['pulse', 'thyroid', 'eyes', 'weight'],
  }),
]);

const prompts = Object.freeze([
  Object.freeze({
    id: 'nora-ask-sleep', text: 'How has your sleep changed, and when do you wake?', stance: 'question',
    noteKey: 'nora-sleep', noteSummary: 'Patient wakes repeatedly in the night and is exhausted by morning.',
    dialogue: '“I go off readily enough from weariness, but then I wake—once, twice, sometimes more. There is no particular dream. I simply find myself staring into the dark, and by morning I am fit for nothing.”',
    effects: { satisfaction: 1 }, appraisal: { register: 'clinical', decorumBreach: 0, intent: 'sleep history' },
  }),
  Object.freeze({
    id: 'nora-ask-onset', text: 'What was happening in your life when the shaking began?', stance: 'question',
    noteSummary: 'Sleep disturbance worsened around her sister Mary’s illness and death in January.',
    discloseFactIds: ['nora-bereavement'], dialogue: '“After Christmas, I think. No—after Mary was taken ill. She was my elder sister. I had been sleeping poorly before she died in January, but not in this fashion.”',
    effects: { satisfaction: 2 }, appraisal: { register: 'courteous', decorumBreach: 0, intent: 'onset' },
    bodyCue: 'sitting-self-soothing',
  }),
  Object.freeze({
    id: 'nora-ask-work', text: 'What work do you do, and what would a long rest mean for you?', stance: 'question',
    noteSummary: 'Patient depends on copyist wages for her room and cannot afford prolonged rest.',
    discloseFactIds: ['nora-work-risk'], dialogue: '“I copy contracts and correspondence for Mr. Pritchard. He has said nothing yet, but he notices errors. If I am kept from the office, there will be no wages and then no room at Mrs. Doyle’s. I have no family purse to draw upon.”',
    effects: { satisfaction: 3 }, appraisal: { register: 'courteous', decorumBreach: 0, intent: 'social history' },
  }),
  Object.freeze({
    id: 'nora-ask-grief', text: 'Since Mary died, have others encouraged you to seek signs from her?', stance: 'question',
    noteSummary: 'A fellow boarder brought the patient to a spiritualist circle where her hand was watched for signs from Mary.',
    requiresFactIds: ['nora-bereavement'], discloseFactIds: ['nora-seance'],
    dialogue: '“A woman at Mrs. Doyle’s—Mrs. Bell—pressed me to attend a circle with her. I went once to oblige her. Then my hand moved, and they said Mary might be trying to speak. You will not put ‘spiritualism’ in your account as though I were a fool, will you?”',
    effects: { trust: 2, satisfaction: 3 }, appraisal: { register: 'courteous', decorumBreach: 0, intent: 'social suggestion' },
    bodyCue: 'sitting-self-soothing',
  }),
  Object.freeze({
    id: 'nora-ask-hand-agency', text: 'When the hand moves, does it ever form words without your deciding what to write?', stance: 'question',
    noteSummary: 'Patient says her left hand writes while she feels she is only watching it.',
    requiresAnyFactIds: ['nora-bereavement', 'nora-seance'], discloseFactIds: ['nora-automatic-writing'],
    dialogue: '“If they place a pencil in my left hand, it may begin before I mean to write. I see the words forming, but it feels more like watching another person’s hand than using my own. I know how unlikely that sounds.”',
    effects: { satisfaction: 1 }, appraisal: { register: 'clinical', decorumBreach: 0, intent: 'automatic writing' },
    bodyCue: 'sitting-self-soothing',
  }),
  Object.freeze({
    id: 'nora-reassure', text: 'You may describe even the strangest part without fear of ridicule.', stance: 'reassure',
    noteSummary: 'A fellow boarder brought the patient to a spiritualist circle where her hand was watched for signs from Mary.',
    requiresFactIds: ['nora-bereavement'], discloseFactIds: ['nora-seance'],
    dialogue: '“Very well. Mrs. Bell took me to a circle, and there my hand began moving when they gave me a pencil. They said it might be Mary. I have not known whether to believe them, but I have been ashamed to tell a physician.”',
    effects: { trust: 6, satisfaction: 5 }, appraisal: { register: 'courteous', decorumBreach: 0, intent: 'reassurance' },
  }),
  Object.freeze({
    id: 'nora-ask-memory', text: 'Do you remember everything that happens while the writing occurs?', stance: 'question',
    noteSummary: 'Patient reports three gaps of ten to twenty minutes despite apparently purposeful behavior.',
    requiresFactIds: ['nora-automatic-writing'], discloseFactIds: ['nora-missing-time'],
    dialogue: '“Not all of it. Three times I have found that part of the hour was gone. Mrs. Bell says I answered when spoken to and once gathered the papers into a neat pile. I remember seeing the pencil at first, and then—nothing until afterward.”',
    effects: { trust: 1, satisfaction: 1 }, appraisal: { register: 'clinical', decorumBreach: 0, intent: 'amnesia' },
    bodyCue: 'sitting-disbelief',
  }),
  Object.freeze({
    id: 'nora-ask-messages', text: 'Have the messages revealed anything you could not already have known?', stance: 'question',
    noteSummary: 'The writings use Mary’s name and familiar phrases but reveal nothing unknown to the patient.',
    requiresFactIds: ['nora-automatic-writing'], discloseFactIds: ['nora-message-limits'],
    dialogue: '“No, that is what troubles me. It signs Mary’s name and uses little sayings we had between us, but it has never told anything I did not already know. Mrs. Bell thinks that proves nothing. I am less certain.”',
    effects: { satisfaction: 1 }, appraisal: { register: 'clinical', decorumBreach: 0, intent: 'message content' },
  }),
  Object.freeze({
    id: 'nora-ask-seizures', text: 'During these gaps, have you fallen, convulsed, bitten your tongue, or remained confused?', stance: 'question',
    noteSummary: 'No falls, convulsions, tongue injury, incontinence, or confusion follow the episodes.',
    requiresFactIds: ['nora-missing-time'], discloseFactIds: ['nora-seizure-negatives'],
    dialogue: '“No, never a fall or a fit. I have not bitten my tongue or spoiled my clothes. They say I remain quiet and answer sensibly. Afterward I am not dazed, exactly—only frightened to find that the minutes belong to everyone but me.”',
    effects: { satisfaction: 0 }, appraisal: { register: 'clinical', decorumBreach: 0, intent: 'seizure differential' },
  }),
  Object.freeze({
    id: 'nora-challenge', text: 'Could you be producing the writing deliberately to attract attention?', stance: 'challenge',
    noteKey: 'nora-denies-fraud', noteSummary: 'Patient denies deliberate production and says fear and the need to keep working brought her to treatment.',
    requiresFactIds: ['nora-automatic-writing'],
    dialogue: '“If I wanted notice, Doctor, I should hardly have chosen this. I came because I am frightened and because I must keep my place. I did not come to be called a fraud.”',
    effects: { trust: -13, satisfaction: -18 }, appraisal: { register: 'prying', decorumBreach: 1, intent: 'accusation' },
    bodyCue: 'sitting-disapproval',
  }),
]);

const inquiryIntents = Object.freeze([
  Object.freeze({
    id: 'nora-intent-automatic-writing', matchTerms: ['write without', 'writing', 'pencil', 'hand move', 'control your hand', 'automatic'],
    noteSummary: 'Patient says her left hand writes while she feels she is only watching it.',
    discloseFactIds: ['nora-automatic-writing'], minimumTrust: 52,
    dialogue: '“Yes. It is the left hand. Once the pencil is there it may start before I have decided on a word. I can see what it writes, but I do not feel that I am composing it.”',
    effects: { satisfaction: 1 }, appraisal: { register: 'clinical', decorumBreach: 0, intent: 'automatic writing' },
    bodyCue: 'sitting-self-soothing',
  }),
  Object.freeze({
    id: 'nora-intent-amnesia', matchTerms: ['lose time', 'missing time', 'remember everything', 'memory', 'blank', 'gap'],
    noteSummary: 'Patient reports three gaps of ten to twenty minutes despite apparently purposeful behavior.',
    requiresFactIds: ['nora-automatic-writing'], discloseFactIds: ['nora-missing-time'], minimumTrust: 58,
    dialogue: '“There have been three gaps—ten minutes perhaps, or twenty. That is Mrs. Bell’s reckoning. She says I spoke quite ordinarily. I remember none of it, which is what frightens me.”',
    effects: { trust: 1 }, appraisal: { register: 'clinical', decorumBreach: 0, intent: 'amnesia' },
    bodyCue: 'sitting-disbelief',
  }),
  Object.freeze({
    id: 'nora-intent-bereavement', matchTerms: ['sister', 'mary', 'died', 'death', 'grief', 'loss', 'when did it begin'],
    noteSummary: 'Sleep disturbance worsened around her sister Mary’s illness and death in January.',
    discloseFactIds: ['nora-bereavement'],
    dialogue: '“My sister Mary died in January. I thought the poor sleep belonged only to grief at first, but it has gone on, and the shaking came afterward—or perhaps just before. I cannot place it exactly.”',
    effects: { satisfaction: 2 }, appraisal: { register: 'courteous', decorumBreach: 0, intent: 'bereavement' },
  }),
  Object.freeze({
    id: 'nora-intent-seance', matchTerms: ['seance', 'séance', 'spiritualist', 'circle', 'spirit', 'dead speaking'],
    noteSummary: 'A fellow boarder brought the patient to a spiritualist circle where her hand was watched for signs from Mary.',
    requiresFactIds: ['nora-bereavement'], discloseFactIds: ['nora-seance'], minimumTrust: 50,
    dialogue: '“Mrs. Bell, who lodges in the same house, took me to a circle. They watched my hand for a sign from Mary. I went only because she pressed me, at least the first time.”',
    effects: { trust: 2 }, appraisal: { register: 'courteous', decorumBreach: 0, intent: 'séance' },
  }),
  Object.freeze({
    id: 'nora-intent-message-content', matchTerms: ['what did it say', 'messages say', 'message', 'anything unknown', 'could not know'],
    noteSummary: 'The writings use Mary’s name and familiar phrases but reveal nothing unknown to the patient.',
    requiresFactIds: ['nora-automatic-writing'], discloseFactIds: ['nora-message-limits'],
    dialogue: '“Nothing I could not have known. It uses Mary’s name and phrases from home. That is why I cannot decide whether the writing means anything at all.”',
    appraisal: { register: 'clinical', decorumBreach: 0, intent: 'message content' },
  }),
  Object.freeze({
    id: 'nora-intent-work', matchTerms: ['work', 'job', 'office', 'pay rent', 'room', 'afford rest'],
    noteSummary: 'Patient depends on copyist wages for her room and cannot afford prolonged rest.',
    discloseFactIds: ['nora-work-risk'],
    dialogue: '“I must keep my place at the law office. Without the wages I cannot keep my room, and there is no one who can simply maintain me while I rest.”',
    effects: { satisfaction: 3 }, appraisal: { register: 'courteous', decorumBreach: 0, intent: 'social history' },
  }),
  Object.freeze({
    id: 'nora-intent-seizure', matchTerms: ['seizure', 'fit', 'convulsion', 'bite your tongue', 'fall down', 'confused afterward'],
    noteSummary: 'No falls, convulsions, tongue injury, incontinence, or confusion follow the episodes.',
    requiresFactIds: ['nora-missing-time'], discloseFactIds: ['nora-seizure-negatives'],
    dialogue: '“There has been no fit and no fall. They tell me I remain quiet. When I come to myself I know where I am; I simply do not know where the missing minutes have gone.”',
    appraisal: { register: 'clinical', decorumBreach: 0, intent: 'seizure differential' },
  }),
  Object.freeze({
    id: 'nora-intent-fraud', matchTerms: ['pretend', 'faking', 'fake', 'attention', 'making it up'],
    noteKey: 'nora-denies-fraud', noteSummary: 'Patient denies deliberate production and says she came from fear and the need to keep working.',
    dialogue: '“I expected you might doubt the story. I did not expect to be accused of inventing it. If that is your judgment, there is little use in my remaining.”',
    effects: { trust: -12, satisfaction: -16 }, appraisal: { register: 'prying', decorumBreach: 1, intent: 'accusation' },
    bodyCue: 'sitting-disapproval',
  }),
]);

export const NORA_BYRNE = Object.freeze({
  id,
  label: 'Miss Nora Byrne',
  contentStatus: 'research-draft',
  profileStatus: 'authored-composite',
  initialTrust: 58,
  initialSatisfaction: 50,
  profile,
  actor,
  opening: Object.freeze({
    dialogue: '“It is my hands, Doctor. They shake at the office, and I do not sleep as I should.”',
    behavior: 'Miss Byrne sits very upright on the edge of the chair, her gloves folded tightly in her lap. A faint tremor passes through her left hand when she notices you looking at it.',
  }),
  groundTruth: Object.freeze({
    etiologyId: 'trauma-related-dissociation-with-functional-symptoms',
    modernSummary: 'A fictional presentation of dissociative amnesia with functional neurological symptoms following bereavement, overwork, and sleep disruption.',
    precipitatingFactors: ['bereavement', 'overwork', 'sleep disruption'],
    shapingFactors: ['spiritualist expectations', 'attention to automatic writing'],
    maintainingFactors: ['fear of the episodes', 'repeated séance participation', 'economic strain'],
    exclusions: ['malingering', 'epileptic seizure', 'structural neurological disease', 'intoxication', 'supernatural knowledge'],
  }),
  sources: Object.freeze([
    Object.freeze({ id: 'james-bourne', citation: 'William James, The Principles of Psychology (1890), vol. 1, pp. 391–393.', supports: ['purposeful behavior during amnesia', 'spontaneous trance as a period comparison'] }),
    Object.freeze({ id: 'james-lucie', citation: 'William James, The Principles of Psychology (1890), vol. 1, p. 228.', supports: ['automatic writing in an insensible hand', 'spirit interpretation shaped by social surroundings'] }),
    Object.freeze({ id: 'janet-lucie', citation: 'Pierre Janet, L’Automatisme psychologique (1889), p. 200 and surrounding experiments.', supports: ['automatic writing and divided awareness'] }),
    Object.freeze({ id: 'dana', citation: 'Charles L. Dana, Text-book of Nervous Diseases (1892), pp. 416–430.', supports: ['period differential: hysteria, tremor, sensory loss, trance, and cerebral automatism'] }),
  ]),
  facts,
  prompts,
  inquiryIntents,
  interpretations: Object.freeze([
    Object.freeze({
      id: 'nora-approach-history',
      text: 'I should learn how this began and what was happening in her family and daily life before I draw conclusions.',
      alignment: 2,
      nextMode: 'patient',
    }),
    Object.freeze({
      id: 'nora-approach-examination',
      text: 'An examination may disclose an ordinary bodily cause for the tremor before I question her further.',
      alignment: 1,
      nextMode: 'examination',
    }),
    Object.freeze({
      id: 'nora-approach-hysteria',
      text: 'At first glance this resembles a textbook hysterical affection; I should test that impression as I proceed.',
      alignment: 0,
      nextMode: 'patient',
      provisionalDiagnosisId: 'nora-dx-automatism',
    }),
  ]),
  dialogueStyle: 'Nora is guarded, concrete, and self-supporting. She speaks in complete but unpolished sentences, sometimes corrects her chronology, and worries about sounding foolish. Keep replies conversational rather than diagnostic. Do not add facts.',
  thoughtIntents: Object.freeze([
    Object.freeze({ id: 'dissociation', label: 'Divided awareness or cerebral automatism', matchTerms: ['double consciousness', 'dissociation', 'automatism', 'divided', 'memory state', 'unconscious writing'], alignment: 3 }),
    Object.freeze({ id: 'functional', label: 'Functional nervous symptom', matchTerms: ['functional', 'hysteria', 'suggestion', 'attention changes'], alignment: 2 }),
    Object.freeze({ id: 'organic', label: 'Organic nervous disease', matchTerms: ['organic', 'epilepsy', 'thyroid', 'brain disease', 'nerve damage'], alignment: 0 }),
    Object.freeze({ id: 'fraud', label: 'Deliberate production', matchTerms: ['fraud', 'malingering', 'pretend', 'faking'], alignment: -2 }),
    Object.freeze({ id: 'spirit', label: 'Spirit influence', matchTerms: ['spirit', 'ghost', 'mary communicating', 'supernatural'], alignment: -1 }),
  ]),
  examinations: Object.freeze([
    Object.freeze({ id: 'nora-exam-tremor', label: 'Observe the extended hands', factId: 'nora-observed-tremor', reply: facts.find((fact) => fact.id === 'nora-observed-tremor').value, uncertainty: 'Attention changes the sign; this is useful evidence but not proof of a cause.', effects: { satisfaction: 0 }, bodyCue: 'sitting-self-soothing' }),
    Object.freeze({ id: 'nora-exam-sensation', label: 'Map touch and pin sensation', factId: 'nora-sensory-pattern', reply: facts.find((fact) => fact.id === 'nora-sensory-pattern').value, uncertainty: 'The boundary is based on repeated reports and remains subjective.', effects: { satisfaction: -1 } }),
    Object.freeze({ id: 'nora-exam-neurology', label: 'Test strength and reflexes', factId: 'nora-normal-neurology', reply: facts.find((fact) => fact.id === 'nora-normal-neurology').value, uncertainty: 'Normal findings reduce some structural explanations but do not settle the case.', effects: { satisfaction: 0 } }),
    Object.freeze({ id: 'nora-exam-thyroid', label: 'Take pulse and inspect eyes and neck', factId: 'nora-thyroid-negative', reply: facts.find((fact) => fact.id === 'nora-thyroid-negative').value, uncertainty: 'A brief office examination cannot exclude every bodily disease.', effects: { satisfaction: 0 } }),
  ]),
  diagnoses: Object.freeze([
    Object.freeze({ id: 'nora-dx-automatism', label: 'Hysteria with cerebral automatism', description: 'A period formulation joining the sensory signs, amnesia, and automatic acts.', evaluation: { quality: 10, patientAcceptance: 1 } }),
    Object.freeze({ id: 'nora-dx-double-consciousness', label: 'Spontaneous hypnotic trance', description: 'A plausible period account of the amnesic intervals, but narrower than the whole presentation.', evaluation: { quality: 8, patientAcceptance: 1 } }),
    Object.freeze({ id: 'nora-dx-neurasthenia', label: 'Neurasthenic exhaustion', description: 'Fits fatigue and sleep loss but does not explain the full pattern.', evaluation: { quality: 5, patientAcceptance: 3 } }),
    Object.freeze({ id: 'nora-dx-epilepsy', label: 'Epileptic automatism', description: 'An important differential weakened by the history and examination.', evaluation: { quality: 3, patientAcceptance: -1 } }),
    Object.freeze({ id: 'nora-dx-basedow', label: 'Basedow’s disease', description: 'The tremor suggests it, but the supporting physical signs are absent.', evaluation: { quality: 1, patientAcceptance: -1 } }),
    Object.freeze({ id: 'nora-dx-malingering', label: 'Malingering', description: 'Regard the symptoms and writing as consciously produced for attention or advantage.', evaluation: { quality: 0, patientAcceptance: -20 } }),
    Object.freeze({ id: 'nora-dx-spirit', label: 'Spirit control', description: 'Regard the writing as communication from Mary through an external agency.', evaluation: { quality: 0, patientAcceptance: 9 } }),
  ]),
  treatments: Object.freeze([
    Object.freeze({ id: 'nora-tx-support', label: 'Support, sleep, continued work, and observation', description: 'Reduce séance exposure, protect ordinary occupation, improve food and sleep, and arrange return visits.', evaluation: { quality: 10, patientAcceptance: 6, healthChange: 7, functionChange: 5, episodesChange: -5, incomeChangeCents: 0, immediateText: 'The practical attention to her work and lodging makes the advice feel possible to follow.', monthText: 'A month later, Miss Byrne has remained at work, sleeps more regularly, and has stopped attending the circle. The gaps have not recurred and the tremor is less frequent.', modernText: 'The supportive plan reduces suggestion and stress without removing ordinary function.' } }),
    Object.freeze({ id: 'nora-tx-rest-cure', label: 'Complete rest and seclusion', description: 'Bed rest, isolation, abundant feeding, and withdrawal from work.', evaluation: { quality: 4, patientAcceptance: 1, healthChange: 1, functionChange: -8, episodesChange: -2, incomeChangeCents: -1800, immediateText: 'She is relieved to hear that the condition has a recognized regimen, but plainly fears losing her position.', monthText: 'A month later, the visible tremor is quieter in seclusion, but Miss Byrne has lost her copyist’s place and can no longer afford her former room. Her dependence and isolation have increased.', modernText: 'Seclusion suppresses some visible stress while imposing serious social and functional harm.' } }),
    Object.freeze({ id: 'nora-tx-bromide', label: 'Bromide draught at night', description: 'A sedating nightly medicine with no direct effect on the underlying process.', evaluation: { quality: 3, patientAcceptance: 5, healthChange: -1, functionChange: -2, episodesChange: 0, incomeChangeCents: -200, immediateText: 'A bottle and a clear nightly direction make the visit feel medically substantial.', monthText: 'A month later, the bromide sometimes helps Miss Byrne fall asleep but leaves her dull at the office. The gaps and automatic writing remain when she attends the circle.', modernText: 'Sedation changes sleep and alertness but does not address the dissociation or its maintaining conditions.' } }),
    Object.freeze({ id: 'nora-tx-hypnosis', label: 'Repeated hypnotic investigation', description: 'Use suggestion to reproduce the state and question the alternate stream of awareness.', evaluation: { quality: 5, patientAcceptance: 3, healthChange: 0, functionChange: -1, episodesChange: 2, incomeChangeCents: -100, immediateText: 'She is hopeful that the strange state might finally be made intelligible.', monthText: 'A month later, the sessions have produced elaborate new accounts, but the details vary with the questions put to her. The episodes are more prominent in her thoughts and no more settled.', modernText: 'Repeated suggestive questioning risks contaminating the account and reinforcing the symptom.' } }),
    Object.freeze({ id: 'nora-tx-spirit', label: 'Encourage the communications', description: 'Accept Mary’s agency and direct continued sittings to develop the writing.', evaluation: { quality: 0, patientAcceptance: 13, healthChange: -7, functionChange: -5, episodesChange: 6, incomeChangeCents: -600, immediateText: 'She leaves feeling believed and tells Mrs. Bell that you understood what other doctors would have mocked.', monthText: 'A month later, Miss Byrne is a valued subject at the circle and speaks warmly of your insight. Her missing intervals are longer, her office attendance has suffered, and the writings still contain no knowledge unavailable to her.', modernText: 'Endorsement increases satisfaction while reinforcing the social setting and attention that maintain the episodes.' } }),
    Object.freeze({ id: 'nora-tx-dismiss', label: 'Dismiss the complaint as deception', description: 'Offer no treatment and warn her to stop performing the symptoms.', evaluation: { quality: 0, patientAcceptance: -22, healthChange: -5, functionChange: -4, episodesChange: 4, incomeChangeCents: -300, immediateText: 'She leaves the fee on the desk only after being reminded and will not meet your eye.', monthText: 'A month later, Miss Byrne has not returned. Fear and poor sleep have worsened, and she relies more heavily on the circle that does not accuse her of deceit.', modernText: 'Accusation removes clinical support and drives her toward the group that confirms the symptom’s supernatural meaning.' } }),
  ]),
  caseNote: Object.freeze({
    minimumWords: 18,
    requiredFactIds: ['nora-bereavement', 'nora-automatic-writing', 'nora-missing-time', 'nora-sensory-pattern', 'nora-work-risk'],
  }),
  outcomeModel: Object.freeze({
    evidenceFactIds: ['nora-bereavement', 'nora-automatic-writing', 'nora-missing-time', 'nora-message-limits', 'nora-seizure-negatives', 'nora-sensory-pattern', 'nora-normal-neurology', 'nora-work-risk'],
    criticalFactIds: ['nora-automatic-writing', 'nora-missing-time', 'nora-sensory-pattern', 'nora-normal-neurology'],
    fee: Object.freeze({ full: 300, reduced: 150 }),
    immediateNarratives: Object.freeze({
      high: 'Miss Byrne rises with visible relief and thanks you warmly. She believes the consultation was worth its cost.',
      middle: 'Miss Byrne thanks you with reserve. She appears uncertain, but does not feel that the visit was wasted.',
      low: 'Miss Byrne rises stiffly. Her brief thanks cannot conceal disappointment and hurt.',
    }),
    monthNarratives: Object.freeze({
      improved: 'Her health and ordinary function have improved.',
      'little-change': 'There has been little material change.',
      worse: 'Her symptoms and ordinary function have worsened.',
      harmed: 'The chosen course has produced substantial harm.',
    }),
    james: Object.freeze({ address: 'My dear Doctor', close: 'Yours faithfully, William James' }),
    modernDebrief: 'From a modern clinical perspective, Nora’s presentation is most consistent with dissociative amnesia and functional neurological symptoms after bereavement, overwork, and disrupted sleep. The automatic writing contains no information Nora did not already possess and provides no evidence of a supernatural source.',
  }),
});
